= B

== block titles

Asciidoc includes markup that you can use to apply a title to a block element.

* We haven't fully defined our usage yet, but in general: Use a block title to provide clarity or sub-structure where the content doesn't warrant a full heading (and built-in anchor).
* Learn about the markup at link:https://docs.asciidoctor.org/asciidoc/latest/blocks/add-title/[Add a Title to a Block^] (external URL).

== brackets

Aside from Asciidoc markup, use brackets in the content as follows:

* Default to round brackets `( )` for most use cases.
Where you use them for parenthesis, try to do this only at the end of a sentence, or -- where appropriate -- consider em dashes instead, as in this sentence.
* Use square brackets `[ ]` where you need to insert a comment or clarification as an editor.
You will also need to type an empty attribute in front, such as `+{blank}+`, to 'escape' them from the normal Asciidoc processing (you could use `+` at each end, but this will escape everything inside, so then URLs and such won't work either).
* Avoid curly brackets `{ }`, except where you have a special use case -- and then you'll need to escape them in the same way as for square brackets.

[[bullets]]
== bullets (unordered lists)

* If you introduce the list with a lead-in sentence, end that sentence with a colon.
* If the bullets are a continuation of a lead-in sentence like this, then:
 ** ensure that each bullet is a single sentence, with no full stops
 ** ensure that every sentence makes sense as a continuation of the lead-in sentence
 ** do not capitalise the first word of each bullet (unless it is a proper noun or acronym of course, as usual)
 ** do not add a full stop or other punctuation at the end of any sentence — not even to the last one
 ** if you really need to create a sentence with more than one (related) clause then use a semi-colon or an em dash -- but don't overdo it
* If the bullets are not a continuation of a lead-in sentence, write the sentences or paragraphs as normal.
See also <<steps>>.