= C
 
== capitalisation

.*Do* capitalise

* Proper nouns (people, places, names, brands): [green]#Ancient Terra#; [green]#the Imperium of Man#.
* Titles of publications.
See also <<citations>>.
* Names of computer languages, protocols and reference standards: [green]#File Transfer Protocol#.
* Special keywords in this project, when you use them in their special sense:
** Keywords for special abilities and super-heavy weapons, such as [green]#{anti-tank}#.
Though in most cases you should use a defined variable which outputs with the correct capitalisation and formatting anyway.
** Unit characteristics, such as [green]#Firepower value#.
** Unit types, such as [green]#War Engine unit#.
+
NOTE: The correct way to pluralise a keyword like War Engine is to add the correct plural noun: [green]#War Engine units#, not [red]#War Engines#.

.*Do not* capitalise

* Compass directions and derivations ([green]#north, east, south and west#; [green]#southern Necromunda#; [green]#the north-western wastelands#) -- unless they form part of an actual or implied proper name for a region.
* Expansions of initialisms, except where the expansion includes words that we would normally capitalise anyway: [green]#super-heavy tank#, not [red]#Super-Heavy Tank (SHT)#.
* Terms that also happen to be special keywords, when we don't use them as such: [green]#intended for an anti-tank role#.
* Terms that can have a particular meaning in the rules, but which do not act as special keywords: [green]#detachment#; [green]#unit type#; [green]#unit#.
+
NOTE: Take extra care with terms that can have a particular meaning, to avoid ambiguity in the rules -- don't mix terms like 'detachment' and 'unit', and don't use synonyms like 'formation'.

*Do not* use [red]#UPPER CASE# for <<emphasis>>.

[[citations]]
== citations

In the absence of other guidance for a particular case, give citations in the following format: <article title>, _<publication, in italics>_, <issue, or date>.
For example: [green]#Path of the Eldar, _White Dwarf_, issue 214.#.

== contractions

Some contractions are okay, as we don't want to sound too formal -- such as [green]#they've#, [green]#we'll#, [green]#can't# and [green]#don't#.

Avoid others like [red]#should've#, [red]#could've# and [red]#would've#, and don't use incorrect perversions of these contractions such as [red]#should of# or [red]#coulda#.
Similarly, avoid [red]#they're# -- or at least use the correct homophone for the context (they're/their/there).