= C

== cannon; cannons

_Cannon_ as a plural is a bit archaic and can appear odd, as in this statement:

"Distortion cannon bore an unstable warp hole in the fabric of reality."
-- Epic 40,000 Rule Book

So, use _cannon_ for the singular and _cannons_ for plural.

== capitalisation

.*Do* capitalise

* Proper nouns (people, places, names, brands): [green]#Ancient Terra#; [green]#the Imperium of Man#.
* Titles of publications.
See also <<citations>>.
* Names of computer languages, protocols and reference standards: [green]#File Transfer Protocol#.
* Special keywords in this project, when you use them in their special sense:
** Keywords for special abilities and super-heavy weapons, such as [green]#{death-ray}#.
Though in most cases, in the Asciidoc source, you should use a defined attribute which outputs with the correct capitalisation and formatting anyway (in this case, you'd type [green]#+{death-ray}+# to invoke the correct attribute).
** Unit characteristics, such as [green]#Firepower value# and [green]#Damage Capacity value#.
** Unit types, such as [green]#War Engine unit#.
+
NOTE: The correct way to pluralise a keyword like War Engine is to add the correct plural noun: [green]#War Engine units#, not [red]#War Engines#.

.*Do not* capitalise

* Compass directions and derivations ([green]#north, east, south and west#; [green]#southern Necromunda#; [green]#the north-western wastelands#) -- unless they form part of an actual or implied proper name for a region.
* Expansions of initialisms, except where the expansion includes words that we would normally capitalise anyway: [green]#super-heavy tank (SHT)#, not [red]#Super-Heavy Tank (SHT)#.
* Terms that also happen to be special keywords, when we don't use them as such: [green]#The Space Marines put up a stubborn resistance#, not [red]#The Space Marines put up a {stubborn} resistance#.
* Terms that can have a particular meaning in the rules, but which do not act as special keywords: [green]#detachment#; [green]#unit type#; [green]#unit#.
+
NOTE: Take extra care with terms that can have a particular meaning, to avoid ambiguity in the rules -- don't mix terms like 'detachment' and 'unit', and don't use synonyms like 'formation'.

*Do not* use [red]#UPPER CASE# for <<emphasis>>.

[[citations]]
== citations

In the absence of other guidance for a particular case, give citations in the following format: <article title>, _<publication, in italics>_, <issue, or date>.
For example: [green]#Path of the Eldar, _White Dwarf_, issue 214#.

Use the same words and capitalisation as in the target publication.

== contractions

Some contractions are okay, as we don't want to sound too formal -- such as [green]#they've#, [green]#we'll#, [green]#can't# and [green]#don't#.

Avoid others like [red]#should've#, [red]#could've# and [red]#would've#, and don't use incorrect perversions of these contractions such as [red]#should of# or [red]#coulda#.
Similarly, avoid [red]#they're# -- or at least use the correct homophone for the context (they're/their/there).