= D

[[dates_and_times]]
== dates and times

There's no one 'right way', but here are some good conventions:

* For a long date format, use `{day name in full} {day number, with ordinals} {month in full} {year, four digits}` with no commas and no 'of' ([green]#Monday 3^rd^ of September 2020#).
* For a short date format, use `{day number, two digits}-{month number, two digits}-{year number, four digits}` ([green]#22-09-2019#).
Or, use the reverse order format when the 'sort order' is important or when there may be confusion with the US 'month first' date format ([green]#2019-09-22#).
* For 12-hour format, always use a colon and [green]#am# or [green]#pm# -- no full stops, and no spaces ([green]#6:30am#).
* For 24-hour format, omit the colon, always use the leading zero for the single-digit hours, and append 'h' ([green]#0630h#).
These rules help to avoid the doubt that can arise from [red]#12:30# or [red]#1230#.
* Use [green]#midnight# and [green]#midday# -- not [red]#12pm#, [red]#noon#, [red]#12 noon#. 
* For a range of time, use the word [green]#to# -- or failing that, use an en dash as stated at <<numbers>>.
* In prose, avoid abbreviation of dates.
If abbreviations are necessary because of space limitations, then use the common three/four letter abbreviations ([green]#Mon#; [green]#Thur#; [green]#Jan#; [green]#Sept#).

.Dates and times
====
Long form: [green]#Monday 4^th^ of September 2020 from 10:30am to 12:30pm.#

Shorter form: [green]#Mon 04 Sept 2020, 10:30am–12:30pm.#

Shortest form: [green]#2020-09-04 1030h–1230h.#
====

== dice; die

Dice = plural of die.
Die = singular of dice.
Use the correct form -- just because some manufacturers can't seem to get it right doesn't mean that we shouldn't!