[[numbers]]
= Numbers

[[digits]]
== 0 to 10, and beyond

=== Numerals or words?

Use numerals, except in these cases in prose where you should use words:

 * Where you use a common expression ([green]#one or two of them#; [green]#three's company#).
 * Where you start a sentence with a number ([green]#Twenty Land Raiders? That's a lot of firepower!#).
 * Where you state a simple fraction ([green]#one half#; [green]#two thirds#).
 * Ordinals one through nine ([green]#first#; [green]#ninth#); thereafter, use the numeral with 'st', 'nd', 'rd' or 'th' as appropriate, in superscript ([green]#8^th^ army#; [green]#41^st^ millennium#; [green]#33^rd^ regiment#).

=== Contractions and units

In general prose, you can use contractions 'k' (thousands), 'm' (millions) and 'bn' (billions) for items and money -- but only with numerals, and never for people or distances.
* When you use a contraction, place it next to the numeral (no space).

For units, use the appropriate abbreviations or symbols in most cases ([green]#10 cm#, not [red]#10 centimetres#).
And in general, use a space to separate these from the numeral just as you would for the full term. Some exceptions where you should *not* use a space include:

* &deg; (degrees); &deg;C (degrees Centigrade)
* " (inches)
* % (percent)

Note that the plural of an abbreviated unit is the same as the singular ([green]#25 cm#, not [red]#25 cms#).  

.Contractions and units
====
[green]#two billion of the Emperor's subjects#, not [red]#two bn#

[green]#4,200 km#, not [red]#4.2k km#

[green]#22.5 MB#, not [red]#22.5MB#

[green]#7bn credits#, not [red]#7 bn credits#

====

=== Other rules for numbers

* For decimal values of less than 1, always include the leading '0' ([green]#0.3#, not [red]#.3#).
* For numerals over 999, insert commas for clarity ([green]#1,000#; [green]#2,500,000#).
* Use [green]#to# in number ranges, or use en dash if you must [green]#–#, not hyphen [red]#-# or em dash [red]#—# ([green]#8 to 12 vehicles#; [green]#8–12 vehicles#). 

.More examples for numbers
====
[none]
* [green]#We fired 7,043 rounds of ammunition#
* [green]#There are three million barrels of fuel at stake# -- or, [green]#There are 3m barrels of fuel at stake#
* [green]#There are 7 million people in that one hive city#
* [green]#A quarter of a million Guardsmen#
* [green]#At a cost of 10bn credits#
* [green]#The first wave of the attack#
* [green]#The 11^th^ planet in the system#
* [green]#Two-thirds of the enemy's total strength#
* [green]#On average, five D6 rolls that require a 4+ result will yield 2.5 hits#
====