= S

== setup; set up

Setup = noun ([green]#Terrain setup#).
Set up = verb ([green]#Set up the terrain#).
Don't hyphenate. 

[[spelling]]
== spelling

Use modern UK English spellings ([green]#immobilised#, not [red]#immobilized#). See also <<localisation>>.
 
== spaces

Do not use double spaces after a full stop or other punctuation -- this became redundant when computers and proportional fonts replaced typewriters and monospace fonts. 

[[steps]] 
== steps (ordered lists)

Use steps to guide a reader through a process.

. Use alphanumeric sequences, not bullets.
. Use a lead-in or stem sentence where appropriate, but try to structure the content so that it is not necessary.
. Punctuate each step normally, to include a full stop at the end of each step.
If you need to include a sub-sequence within a step, use indented lowercase letters. 
 .. Like this. 
 .. And like this. 
. If you need to provide choices or points in which the order is unimportant, use indented bullets (unordered list). 
 ** Like this. 
 ** And like this. 
. And then continue with the next step like this. 

See also <<bullets>>.

== super-heavy

Two words.
Hyphenate.